const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#00C4FF",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#00C4FF",
    primaryForeground: "#000000",
    secondary: "#1A3C6E",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#00C4FF",
    accentForeground: "#000000",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1E1E1E",
    success: "#30D158",
    warning: "#FF9F0A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00C4FF",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#00C4FF",
    primaryForeground: "#000000",
    secondary: "#1A3C6E",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#00C4FF",
    accentForeground: "#000000",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1E1E1E",
    success: "#30D158",
    warning: "#FF9F0A",
  },
  radius: 14,
};

export default colors;
